name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Clone Platane/snk
        run: git clone https://github.com/Platane/snk.git

      - name: Install dependencies
        run: |
          cd snk
          npm install

      - name: Generate SVG with custom colors
        run: |
          cd snk
          npm run build
          node ./dist/index.js \
            --github_user_name=${{ github.repository_owner }} \
            --output=../dist/github-contribution-grid-snake.svg \
            --color_snake="#00ff7f" \
            --color_dots="#161b22,#0e4429,#006d32,#26a641,#39d353" \
            --show_progress_bar=false

      - name: Upload to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
